apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: prod
type: Opaque
data:
  postgres-user-password: cHJvZGtleWNsb2FrcGFzc3dvcmQ=
  postgres-admin-password: cHJvZGtleWNsb2FrcGFzc3dvcmQ=
  keycloak-admin-password: cHJvZGtleWNsb2FrcGFzc3dvcmQ=
