grpc:
  client:
    ai-service:
      address: static://localhost:7070
      negotiationType: PLAINTEXT
server:
  port: 8080
spring:
  application:
    name: interview-core
  graphql:
    path: /graphql
  graphiql:
    enabled: true
    path: /graphiql

  kafka:
    producer:
      bootstrap-servers: localhost:19092,localhost:29092,localhost:39092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 10
      properties:
        delivery:
          timeout:
            ms: 120000
        linger:
          ms: 0
        request:
          timeout:
            ms: 30000
        retry:
          backoff:
            ms: 1000
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ad_db
    username: ad_java
    password: ad_java
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:http://interview-config.dev.svc.cluster.local:9094"
  cloud:
    function:
      definition: updateCommunication
    stream:
      bindings:
        sendCommunication-out-0:
          destination: send-communication
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  flyway:
    user: ad_java
    password: ad_java
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migrations