apiVersion: v2
name: prod-env
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: interview-common
    version: 0.1.0
    repository: file://../../interview-common

  - name: config-server
    version: 0.1.0
    repository: file://../../interview-services/config-server

  - name: eureka-server
    version: 0.1.0
    repository: file://../../interview-services/eureka-server

  - name: interview-backend
    version: 0.1.0
    repository: file://../../interview-services/interview-backend

  - name: interview-ai-backend
    version: 0.1.0
    repository: file://../../interview-services/interview-ai-backend

  - name: notification
    version: 0.1.0
    repository: file://../../interview-services/notification

  - name: gateway-server
    version: 0.1.0
    repository: file://../../interview-services/gateway-server

  - name: postgresql
    version: 15.5.29
    repository: https://charts.bitnami.com/bitnami
    alias: postgresql-interview
    condition: postgresql-interview.enabled

  - name: rabbitmq
    version: 16.0.14
    repository: https://charts.bitnami.com/bitnami
    alias: rabbitmq-interview
    condition: rabbitmq-interview.enabled

  - name: redis
    version: 24.1.0
    repository: https://charts.bitnami.com/bitnami
    alias: redis-interview
    condition: redis-interview.enabled

  - name: keycloak
    version: 25.2.0
    repository: https://charts.bitnami.com/bitnami
    alias: keycloak-interview
    condition: keycloak-interview.enabled
