server:
  port: 8080
spring:
  application:
    name: File
  datasource:
    url: jdbc:postgresql://localhost:5432/ad_db
    username: ad_java
    password: ad_java
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
app:
  storage:
    local:
      base-path: /tmp/file-storage
    default-provider: LOCAL