apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-mac-pv-qa
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mac-keycloak-hostpath
  hostPath:
    path: /Users/maheshlamichhane/volumes/keycloak/qa
    type: DirectoryOrCreate
