apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: qa
type: Opaque
data:
  postgres-user-password: cWFrZXljbG9ha3Bhc3N3b3Jk
  postgres-admin-password: cWFrZXljbG9ha3Bhc3N3b3Jk
  keycloak-admin-password: cWFrZXljbG9ha3Bhc3N3b3Jk
