apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-mac-pvc
  namespace: qa
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mac-hostpath
  resources:
    requests:
      storage: 5Gi
