server:
  port: 8080
spring:
  application:
    name: interview-backend
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:http://config-server:8082/"
  cloud:
#    openfeign:
#      circuitbreaker:
#        enabled: true
    function:
      definition: updateCommunication
    stream:
      bindings:
        sendCommunication-out-0:
          destination: send-communication
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}
#    kubernetes:
#      discovery:
#        all-namespaces: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  datasource:
    url: jdbc:postgresql://localhost:5432/ad_db
    username: ad_java
    password: ad_java
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: maheshlamichhane048@gmail.com
    password: ozst ftox qokj bmjg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
app:
  otp:
    expiry-minutes: 5
    max-attempts: 5
    max-requests-per-hour: 10
    max-requests-per-day: 50
    ip-block-threshold: 20
  storage:
    local:
      base-path: /your/local/storage/path
    default-provider: local

twilio:
  account:
    sid: ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  auth:
    token: your_test_auth_token
  from:
    number: "+15005550006"
  phone:
    number: 34344343

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


#resilience4j.circuitbreaker:
#  configs:
#    default:
#      sliding-window-size: 10
#      permitted-number-of-calls-in-half-open-state: 2
#      failure-rate-threshold: 50
#      wait-duration-in-open-state: 10s

#resilience4j:
#  retry:
#    configs:
#      default:
#        max-attempts: 3
#        wait-duration: 100ms
#        enable-exponential-backoff: true
#        exponential-backoff-multiplier: 2
#        ignore-exceptions:
#          - java.lang.NullPointerException
#        retry-exceptions:
#          - java.util.concurrent.TimeoutException
#          - java.lang.ArrayIndexOutOfBoundsException

#  ratelimiter:
#    configs:
#      default:
#        timeout-duration: 1000
#        limit-refresh-period: 5000
#        limit-for-period: 1
