server:
  port: 8080
spring:
  application:
    name: Interview
  datasource:
    url: jdbc:postgresql://localhost:5432/ad_db
    username: ad_java
    password: ad_java
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: maheshlamichhane048@gmail.com
    password: ozst ftox qokj bmjg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9090/eureka/
app:
  otp:
    expiry-minutes: 5
    max-attempts: 5
    max-requests-per-hour: 10
    max-requests-per-day: 50
    ip-block-threshold: 20
