server:
  port: 8080

spring:
  application:
    name: interview-managing-system
  datasource:
    url: jdbc:postgresql://localhost:5432/ad_db
    username: ad_java
    password: ad_java
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: maheshlamichhane048@gmail.com
    password: ozst ftox qokj bmjg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000