deploymentName: interview-notification-deployment
serviceName: interview-notification
appLabel: interview-notification
appName: interview-notification

replicaCount: 1

image:
  repository: maheshlamichhane123/interview-notification
  tag: s3

containerPort: 9092

service:
  type: ClusterIP
  port: 9092
  targetPort: 9092

appname_enabled: true
profile_enabled: true
config_enabled: true
resouceserver_enabled: false
rabbit_enabled: true
redis_enabled: false
version_enabled: false
