# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ad_db
spring.datasource.username=ad_java
spring.datasource.password=ad_java
spring.jpa.hibernate.ddl-auto=update

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=maheshamichhane048@gmail.com
spring.mail.password=ozst ftox qokj bmjg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Twilio SMS Configuration
twilio.account.sid=ACdd044875452dcb302b64c5f57aeec0eb
twilio.auth.token=1fbb255cee4a28d32045a611a07d6894
twilio.phone.number=+1234567890

# Logging
logging.level.com.example.notification=DEBUG