apiVersion: v1
kind: ConfigMap
metadata:
  name: interview-configmap
  namespace: default
data:

  # Config Server
  SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8082/"
  CONFIGSERVER_APPLICATION_NAME: "configserver"

  # Eureka Server
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8083/eureka/"
  EUREKA_APPLICATION_NAME: "eurekaserver"

  # Interview Services
  INTERVIEW_APPLICATION_NAME: "interviews"
  INTERVIEW_AI_APPLICATION_NAME: "interviews-ai"
  NOTIFICATION_APPLICATION_NAME: "notification"

  # Profile 
  SPRING_PROFILES_ACTIVE: "dev"

  # Gateway
  GATEWAY_APPLICATION_NAME: "gatewayserver"

  # RabbitMQ
  RABBITMQ_HOST: "rabbit"

  # Keycloak / Security
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8084/realms/master/protocol/openid-connect/certs"

  # Redis
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_TIMEOUT: "1s"
  SPRING_DATA_REDIS_CONNECT_TIMEOUT: "2s"

  # PostgreSQL DB For microservice
  POSTGRES_INTERVIEW_DB: "default"
  POSTGRES_INTERVIEW_USER: "default"
  POSTGRES_INTERVIEW_PASSWORD: "default"
  POSTGRES_INTERVIEW_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
  POSTGRES_INTERVIEW_DB_URL: "jdbc:postgresql://postgresqldb:5432/default"




  # PostgreSQL DB For Keycloak
  POSTGRES_KEYCLOAK_DB: "keycloak"
  POSTGRES_KEYCLOAK_USER: "keycloak"
  POSTGRES_KEYCLOAK_PASSWORD: "keycloak"
  POSTGRES_KEYCLOAK_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
  POSTGRES_KEYCLOAK_DB_URL: "jdbc:postgresql://postgresqlkeycloakdb:5432/keycloak"


  # Keycloak DB
  KC_DB: "postgres"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"

