apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresqlkeycloakdb
  labels:
    app: postgresqlkeycloakdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresqlkeycloakdb
  template:
    metadata:
      labels:
        app: postgresqlkeycloakdb
    spec:
      containers:
        - name: postgresqlkeycloakdb
          image: postgres:15-alpine
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: POSTGRES_KEYCLOAK_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: POSTGRES_KEYCLOAK_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: POSTGRES_KEYCLOAK_PASSWORD
            - name: POSTGRES_INITDB_ARGS
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: POSTGRES_KEYCLOAK_INITDB_ARGS

---

apiVersion: v1
kind: Service
metadata:
  name: postgresqlkeycloakdb
  labels:
    app: postgresqlkeycloakdb
spec:
  selector:
    app: postgresqlkeycloakdb
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

