# apiVersion: security.istio.io/v1
# kind: RequestAuthentication
# metadata:
#   name: jwt-auth
#   namespace: dev
# spec:
#   selector:
#     matchLabels:
#       app: interview-admin
#   jwtRules:
#     - issuer: "http://localhost:9095/realms/Interview"
#       jwksUri: "http://dev-env-keycloak-interview.dev.svc.cluster.local:9095/realms/Interview/protocol/openid-connect/certs"
