apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: dev
spec:
  selector:
    matchLabels:
      app: interview-backend
  jwtRules:
    - issuer: "http://localhost:8084/realms/Interview"
      jwksUri: "http://dev-env-keycloak-interview.dev.svc.cluster.local:8084/realms/Interview/protocol/openid-connect/certs"
