version: '3.8'
services:
  postgresqldb:
    container_name: postgresqldb
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U default -d default" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - interview-network

  eurekaserver:
    image: "maheshlamichhane123/eureka-server:s1"
    container_name: eurekaserver-ms
    platform: linux/amd64
    ports:
      - "8084:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - interview-network
    restart: unless-stopped

  interview:
    image: "maheshlamichhane123/interview-backend:s1"
    container_name: interview-backend-ms
    platform: linux/amd64
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      configserver:
        condition: service_healthy
      postgresqldb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresqldb:5432/default"
      SPRING_DATASOURCE_USERNAME: default
      SPRING_DATASOURCE_PASSWORD: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8080/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycoak:8080/realms/Interview"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_RABBITMQ_HOST: "rabbit"

  interview-ai:
    image: "maheshlamichhane123/interview-ai-backend:s1"
    container_name: interview-ai-backend-ms
    platform: linux/amd64
    ports:
      - "8085:8085"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      configserver:
        condition: service_healthy
      postgresqldb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresqldb:5432/default"
      SPRING_DATASOURCE_USERNAME: default
      SPRING_DATASOURCE_PASSWORD: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8080/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycoak:8080/realms/Interview"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_RABBITMQ_HOST: "rabbit"

    networks:
      - interview-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    ports:
      - "8082:8080"
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresqldb:5432/default
      KC_DB_USERNAME: default
      KC_DB_PASSWORD: default
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    depends_on:
      - postgresqldb
    networks:
      - interview-network

  gatewayserver:
    image: "maheshlamichhane123/gateway-server:s1"
    container_name: gateway-ms
    platform: linux/amd64
    ports:
      - "8083:8080"
    healthcheck:
      test: curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      eurekaserver:
        condition: service_healthy
      interview:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8080/eureka/
    networks:
      - interview-network

  rabbit:
    image: rabbitmq:3.13-management
    # hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - interview-network

  configserver:
    image: "maheshlamichhane123/config-server:s1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
    networks:
      - interview-network

volumes:
  postgres_data:


networks:
  interview-network:
    driver: bridge
