global:
  configMapName: interviewdev-configmap
  activeProfile: dev
  configServerURL: http://interview-config.dev.svc.cluster.local:9094/
  keyCloakURL: http://dev-env-keycloak-interview.dev.svc.cluster.local:9095/realms/master/protocol/openid-connect/certs
  rabbitBrokerURL: dev-env-rabbitmq-interview.dev.svc.cluster.local
  redisURL: dev-env-redis-interview-master.dev.svc.cluster.local

postgresql-interview:
  global:
    postgresql:
      auth:
        enablePostgresUser: true
        username: devuser
        password: ""
        database: interviewdb
        existingSecret: interviewdb
        secretKeys:
          adminPasswordKey: postgres-admin-password
          userPasswordKey: postgres-user-password
          replicationPasswordKey: postgres-user-password
      service:
        ports:
          postgresql: "5442"
  auth:
    secretKeys:
      adminPasswordKey: postgres-admin-password
      userPasswordKey: postgres-user-password
      replicationPasswordKey: postgres-user-password
  primary:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      existingClaim: postgres-mac-pvc
  image:
    repository: bitnamilegacy/postgresql

rabbitmq-interview:
  image:
    repository: bitnamilegacy/rabbitmq
  auth:
    existingPasswordSecret: rabbitmq
    existingSecretPasswordKey: password
  global:
    security:
      allowInsecureImages: true
  service:
    type: ClusterIP

redis-interview:
  image:
    repository: bitnamilegacy/redis
  auth:
    existingSecret: redis
    existingSecretPasswordKey: password
  global:
    security:
      allowInsecureImages: true
  replica:
    replicaCount: 1

keycloak-interview:
  image:
    repository: bitnamilegacy/keycloak
  auth:
    adminUser: admin
    existingSecret: keycloak
    passwordSecretKey: keycloak-admin-password
  service:
    type: ClusterIP
    ports:
      http: 9095
  postgresql:
    enabled: true
    image:
      repository: bitnamilegacy/postgresql
    auth:
      postgresPassword: postgres-admin-password
      username: keycloak
      existingSecret: keycloak
      secretKeys:
        userPasswordKey: postgres-user-password
    primary:
      persistence:
        enabled: true
        existingClaim: keycloak-mac-pvc
