package com.ai.project.enums;

public enum AIServiceType {
    INTERVIEW_ANALYSIS,
    RESUME_PARSING,
    QUESTION_GENERATION,
    SENTIMENT_ANALYSIS,
    TRANSCRIPT_SUMMARIZATION,
    SKILL_MATCHING,
    JOB_DESCRIPTION_GENERATION,
    FEEDBACK_GENERATION,
    BEHAVIORAL_ANALYSIS,
    CODE_EVALUATION
}
