<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.interviews</groupId>
	<artifactId>interview-parent</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>interview-parent</name>
	<description>Parent BOM for  interview microservices</description>
    <packaging>pom</packaging>

    <url>www.interview.com</url>
    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>Mahesh Lamichhane</name>
            <email>maheshlamichhane048@gmail.com</email>
            <organization>interviews</organization>
            <organizationUrl>www.interviews.com</organizationUrl>
        </developer>
    </developers>
    <scm>
        <url>https://github.com/maheshlamichhane/microservices</url>
    </scm>

    <properties>
        <common-lib.version>1.0.0</common-lib.version>
        <java.version>21</java.version>
        <maven.compiler.release>21</maven.compiler.release>
        <spring-boot.version>3.4.13</spring-boot.version>
        <spring-cloud.version>2024.0.0</spring-cloud.version>
        <lombok.version>1.18.42</lombok.version>
        <jib.version>3.4.1</jib.version>
        <image.tag>s10</image.tag>
        <testcontainers.version>1.19.8</testcontainers.version>

        <grpc.java.version>1.58.0</grpc.java.version>
        <tomcat.annotations.version>6.0.53</tomcat.annotations.version>
        <protoc.version>3.24.0</protoc.version>
        <protobuf.maven.plugin.version>0.6.1</protobuf.maven.plugin.version>
        <os.maven.plugin.version>1.7.1</os.maven.plugin.version>
        <grpc.spring.version>2.15.0.RELEASE</grpc.spring.version>
        <protobuf.java.util.version>3.25.4</protobuf.java.util.version>
    </properties>


	<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
	</dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-test</artifactId>
                <version>${spring-boot.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>${os.maven.plugin.version}</version>
            </extension>
        </extensions>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.xolstice.maven.plugins</groupId>
                    <artifactId>protobuf-maven-plugin</artifactId>
                    <version>${protobuf.maven.plugin.version}</version>
                    <configuration>
                        <!--suppress UnresolvedMavenProperty -->
                        <protocArtifact>
                            com.google.protobuf:protoc:${protoc.version}:exe:${os.detected.classifier}
                        </protocArtifact>
                        <pluginId>grpc-java</pluginId>
                        <!--suppress UnresolvedMavenProperty -->
                        <pluginArtifact>
                            io.grpc:protoc-gen-grpc-java:${grpc.java.version}:exe:${os.detected.classifier}
                        </pluginArtifact>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>


</project>
