apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: interview-gateway
  namespace: dev
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.interview-app.com"
        - "interview-app.com"
