apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ingress-interview-core-service-destinationrule
  namespace: dev
spec:
  host: interview-core.dev.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
