apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak-container
          image: quay.io/keycloak/keycloak:24.0.1
          args: ["start-dev","--http-port=8084"]
          ports:
            - name: http
              containerPort: 8084
          env:
            - name: KC_DB
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: KC_DB
            - name: KC_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key:  POSTGRES_KEYCLOAK_DB_URL
            - name: KC_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: POSTGRES_KEYCLOAK_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: POSTGRES_KEYCLOAK_PASSWORD
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: KEYCLOAK_ADMIN_PASSWORD
---

apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8084
      targetPort: 8084

