apiVersion: v1
kind: ConfigMap
metadata:
  name: interview-configmap
  namespace: default
data:

  # Config Server
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8082/"

  # Eureka Server
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8083/eureka/"

  # Profile 
  SPRING_PROFILES_ACTIVE: "dev"

  # Gateway
  GATEWAY_APPLICATION_NAME: "gatewayserver"

  # RabbitMQ
  RABBITMQ_HOST: "rabbit"

  # Keycloak / Security
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8084/realms/master/protocol/openid-connect/certs"

  # Redis
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_TIMEOUT: "1s"
  SPRING_DATA_REDIS_CONNECT_TIMEOUT: "2s"


  # PostgreSQL DB for interview microservice
  POSTGRES_INTERVIEW_DB: "interview"
  POSTGRES_INTERVIEW_USER: "interview"
  POSTGRES_INTERVIEW_PASSWORD: "interview"
  POSTGRES_INTERVIEW_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
  POSTGRES_INTERVIEW_DB_URL: "jdbc:postgresql://postgresql-interview-db:5443/interview"


  # PostgreSQL DB for interview ai microservice
  POSTGRES_INTERVIEWAI_DB: "interviewai"
  POSTGRES_INTERVIEWAI_USER: "interviewai"
  POSTGRES_INTERVIEWAI_PASSWORD: "interviewai"
  POSTGRES_INTERVIEWAI_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
  POSTGRES_INTERVIEWAI_DB_URL: "jdbc:postgresql://postgresql-interviewai-db:5444/interviewai"




  # PostgreSQL DB For Keycloak
  POSTGRES_KEYCLOAK_DB: "keycloak"
  POSTGRES_KEYCLOAK_USER: "keycloak"
  POSTGRES_KEYCLOAK_PASSWORD: "keycloak"
  POSTGRES_KEYCLOAK_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
  POSTGRES_KEYCLOAK_DB_URL: "jdbc:postgresql://postgresql-keycloak-db:5442/keycloak"


  # Keycloak DB
  KC_DB: "postgres"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"

