apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server-container
          image: maheshlamichhane123/config-server:s2
          ports:
            - name: http
              containerPort: 8082
          env:
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: RABBITMQ_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  selector:
    app: config-server
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
