apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  labels:
    app: gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server-container
          image: maheshlamichhane123/gateway-server:s2
          ports:
            - name: http
              containerPort: 8085
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATA_REDIS_CONNECT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: SPRING_DATA_REDIS_CONNECT_TIMEOUT
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: SPRING_DATA_REDIS_HOST
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: SPRING_DATA_REDIS_PORT
            - name: SPRING_DATA_REDIS_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: SPRING_DATA_REDIS_TIMEOUT
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  labels:
    app: gateway-server
spec:
  selector:
    app: gateway-server
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8085
      targetPort: 8085

