apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-ai-backend
  labels:
    app: interview-ai-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interview-ai-backend
  template:
    metadata:
      labels:
        app: interview-ai-backend
    spec:
      containers:
        - name: interview-ai-backend-container
          image: maheshlamichhane123/interview-ai-backend:s1
          ports:
            - name: http
              containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: POSTGRES_INTERVIEWAI_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: POSTGRES_INTERVIEWAI_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: POSTGRES_INTERVIEWAI_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: interview-configmap
                  key: RABBITMQ_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: interview-backend
  labels:
    app: interview-backend
spec:
  selector:
    app: interview-backend
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081

