apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: interview-api
  namespace: dev
spec:
  hosts:
    - "api.interview-app.com"
  gateways:
    - dev/interview-gateway
  http:
    # - match:
    #     - uri:
    #         prefix: /api/interviews
    #       method:
    #         exact: GET
    #   route:
    #     - destination:
    #         host: interview-backend.dev.svc.cluster.local
    #         port:
    #           number: 8080
    #   timeout: 60s

    - match:
        - uri:
            prefix: /api/interviews
      route:
        - destination:
            host: interview-backend.dev.svc.cluster.local
            port:
              number: 8080
      timeout: 60s

    # - match:
    #     - uri:
    #         prefix: /api/ai
    #       method:
    #         exact: GET
    #   route:
    #     - destination:
    #         host: interview-ai-backend.dev.svc.cluster.local
    #         port:
    #           number: 8081
    #   timeout: 120s

    - match:
        - uri:
            prefix: /api/ai
      route:
        - destination:
            host: interview-ai-backend.dev.svc.cluster.local
            port:
              number: 8081
      timeout: 120s
