apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-mac-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mac-keycloak-hostpath
  resources:
    requests:
      storage: 3Gi
