apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: dev
type: Opaque
data:
  postgres-user-password: ZGV2a2V5Y2xvYWtwYXNzd29yZA==
  postgres-admin-password: ZGV2a2V5Y2xvYWtwYXNzd29yZA==
  keycloak-admin-password: ZGV2a2V5Y2xvYWtwYXNzd29yZA==
