apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 9080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: dev-kafka
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "dev-env-kafka-broker-0.dev.svc.cluster.local:9092,dev-env-kafka-broker-1.dev.svc.cluster.local:9092,dev-env-kafka-broker-2.dev.svc.cluster.local:9092"
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: "" # Not needed for KRaft mode
            - name: KAFKA_CLUSTERS_0_SCHEMA_REGISTRY
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: kafka-ui
  ports:
    - name: http
      port: 9080 # Service port
      targetPort: 9080 # Container port

